server:
    port: 9001

spring:
    datasource:
        url: jdbc:mysql://122.51.8.3:3306/db_graduationthesis?useSSL=true&useUnicode=true&characterEncoding=UTF-8
        username: user2
        password: user2
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 配置 HikariCP 连接池以解决 "No operations allowed after connection closed" 警告
        hikari:
            minimum-idle: 3
            maximum-pool-size: 10
            max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
            connection-test-query: SELECT 1

mybatis:
    configuration:
        map-underscore-to-camel-case: true